export const LAPTOP = {
  LAPTOP_GET_LIST: "LAPTOP/GET_LIST",
  LAPTOP_GET_LIST_SUCCESS: "LAPTOP/GET_LIST_SUCCESS",

  LAPTOP_CREATE: "LAPTOP/CREATE",
  CHANGE_PAGE: "LAPTOP/CHANGE_PAGE",
  DELETE_LAPTOP: "LAPTOP/DELETE",
  EDIT_LAPTOP: "LAPTOP/EDIT_LAPTOP"
};
